hook global WinSetOption filetype=(rust|c) %{
  eval %sh{ kak-lsp }
}

# Disable elixir automatic "end"
hook global WinSetOption filetype=elixir %{
    remove-hooks window elixir-insert
}

set global indentwidth 4

hook global WinSetOption filetype=(lisp|haskell) %{
    set window indentwidth 2
    map window insert <tab> <space><space>
}

hook global WinSetOption filetype=(clojure|lisp|picolisp|racket|scheme) %{
    parinfer-enable-window -smart
}

