// Rationale:
// base16 themes are a convenient way to switch themes, but
// * keywords are blue in Nord and red in Ashen. Base16 doesn't understand this.
// * The color 'black' isn't always the background color. So a base16 program that tries to draw white
//   may end up drawing black on a light theme
// * Not all themes have the same amount of contrast. Base16 is terrible with low contrast themes
//
// Limitations:
// Does not understand styles like italic/bold. That is left upto the editor, not the theme(which isn't always true)

// This file defines the fields necessary for a basic theme

// Put the pallette of your theme here

// Replace ... with whatever colors you want. Ideally from the pallette itself

// Basic colors.
// 
// Most themes define multiple levels of background and foreground.
// We must define this seperately because it is not necessary that black is the background
// and white is the foreground. e.g ashen uses orange for brown_dark

// Primary foreground color, also used for text
#define FOREGROUND_1 ...
// Secondary foreground color, used for *more* important things, like bold
#define FOREGROUND_2 ...
// Tertiary foreground color, used for *less* important things(but not comments)
#define FOREGROUND_3 ...

// Primary background color, used for the lowest level of UI(e.g the buffer of a text editor)
#define BACKGROUND_1 ...
// Secondary background color, used for status lines, gutters, etc
#define BACKGROUND_2 ...
// Tertiary background color, used for the most important background elements(e.g text editor selection)
#define BACKGROUND_3 ...

// 16 colors.
// We share this with base16 themes, but these have no semantic meaning.
// They are purely there to support terminals.
#define BLACK ...
#define RED ...
#define GREEN ...
#define YELLOW ...
#define BLUE ...
#define MAGENTA ...
#define CYAN ...
#define WHITE ...

#define BRIGHT_BLACK ...
#define BRIGHT_RED ...
#define BRIGHT_GREEN ...
#define BRIGHT_YELLOW ...
#define BRIGHT_BLUE ...
#define BRIGHT_MAGENTA ...
#define BRIGHT_CYAN ...
#define BRIGHT_WHITE ...

// Syntax highlighting.
//
// Most themes have opinions about what color each part of syntax highlighting should be.
// Hence, we respect that and allow setting the color seperately for each part of code.
// Note that it is impossible to be fully comprehensive for all text editors. These are just what is common in most languages.

#define KEYWORD ...
#define TYPE ...
#define VARIABLE ...
#define FUNCTION ...
#define BUILTIN ...
#define STRING ...
#define NUMBER ...
#define OPERATOR ...
#define COMMENT ...
#define HEADING ...
#define BRACKET ...
#define MATCHING_DELIMITER ...
#define WHITESPACE ...
// Used for the background of `code` in Markdown
#define MONOSPACE_BACKGROUND ...
// Used for macros, preprocessors, etc
#define METAPROGRAMMING ...

// UI Elements
// 
// Many UI Elements have special colors that can't be reduced to BACKGROUND_x or FOREGROUND_x

#define PRIMARY_SELECTION_FOREGROUND ...
#define PRIMARY_SELECTION_BACKGROUND ...
#define SECONDARY_SELECTION_FOREGROUND ...
#define SECONDARY_SELECTION_BACKGROUND ...

// Warnings and Errors. Self explanatory
#define WARNING ...
#define ERROR ...
