// Palette

// Basics
#define FOREGROUND_1 ...
#define FOREGROUND_2 ...
#define FOREGROUND_3 ...

#define BACKGROUND_1 ...
#define BACKGROUND_2 ...
#define BACKGROUND_3 ...

// 16 colors
#define BLACK ...
#define RED ...
#define GREEN ...
#define YELLOW ...
#define BLUE ...
#define MAGENTA ...
#define CYAN ...
#define WHITE ...

#define BRIGHT_BLACK ...
#define BRIGHT_RED ...
#define BRIGHT_GREEN ...
#define BRIGHT_YELLOW ...
#define BRIGHT_BLUE ...
#define BRIGHT_MAGENTA ...
#define BRIGHT_CYAN ...
#define BRIGHT_WHITE ...

// Syntax highlighting
#define KEYWORD ...
#define TYPE ...
#define VARIABLE ...
#define FUNCTION ...
#define BUILTIN ...
#define STRING ...
#define NUMBER ...
#define OPERATOR ...
#define COMMENT ...
#define HEADING ...
#define BRACKET ...
#define MATCHING_DELIMITER ...
#define WHITESPACE ...
#define MONOSPACE_BACKGROUND ...
#define METAPROGRAMMING ...

// UI Elements
#define PRIMARY_SELECTION_FOREGROUND ...
#define PRIMARY_SELECTION_BACKGROUND ...
#define PRIMARY_CURSOR_BACKGROUND ...
#define SECONDARY_SELECTION_FOREGROUND ...
#define SECONDARY_SELECTION_BACKGROUND ...
#define SECONDARY_CURSOR_BACKGROUND ...

// Warnings and Errors
#define WARNING ...
#define ERROR ...
