// Palette
#define BACKGROUND 191919
#define TEXT b4b4b4
#define RED_FLAME c53030
#define RED_GLOWING df6464
#define RED_EMBER b14242
#define ORANGE_GLOW d87c4a
#define ORANGE_BLAZE c4693d
#define ORANGE_MUTED 6d3b22
#define ORANGE_SMOLDER e49a44
#define ORANGE_GOLDEN e5a72a
#define GOLDEN_MUTED 6d4d0d
#define BROWN 89492a
#define BROWN_DARK 322119
#define BROWN_DARKER 22150f
#define BLUE 4a8b8b
#define G_1 e5e5e5
#define G_2 d5d5d5
#define G_3 b4b4b4
#define G_4 a7a7a7
#define G_5 949494
#define G_6 737373
#define G_7 535353
#define G_8 323232
#define G_9 212121
#define G_10 1d1d1d
#define G_11 191919
#define G_12 151515

// Basics
#define FOREGROUND_1 TEXT
#define FOREGROUND_2 G_3
#define FOREGROUND_3 G_7

#define BACKGROUND_1 BACKGROUND
#define BACKGROUND_2 G_9
#define BACKGROUND_3 G_7

// 16 colors
#define BLACK BACKGROUND
#define RED RED_EMBER
#define GREEN ORANGE_GLOW
#define YELLOW ORANGE_SMOLDER
// #define BLUE // already defined
#define MAGENTA G_4
#define CYAN TEXT
#define WHITE G_2

#define BRIGHT_BLACK G_5
#define BRIGHT_RED RED_EMBER
#define BRIGHT_GREEN ORANGE_GLOW
#define BRIGHT_YELLOW ORANGE_SMOLDER
#define BRIGHT_BLUE BLUE
#define BRIGHT_MAGENTA G_4
#define BRIGHT_CYAN TEXT
#define BRIGHT_WHITE G_2

// Syntax highlighting
#define KEYWORD RED_EMBER
#define TYPE BLUE
#define VARIABLE G_3
#define FUNCTION G_3
#define BUILTIN FUNCTION
#define STRING RED_GLOWING
#define NUMBER BLUE
#define OPERATOR ORANGE_GLOW
#define COMMENT G_6
#define HEADING RED_GLOWING
#define MATCHING_DELIMITER ORANGE_SMOLDER
#define WHITESPACE G_7
#define MONOSPACE_BACKGROUND G_10
#define METAPROGRAMMING RED_EMBER

// UI Elements
#define PRIMARY_SELECTION_FOREGROUND TEXT
#define PRIMARY_SELECTION_BACKGROUND BROWN_DARK
#define PRIMARY_CURSOR_BACKGROUND ORANGE_SMOLDER
#define SECONDARY_SELECTION_FOREGROUND TEXT
#define SECONDARY_SELECTION_BACKGROUND BROWN_DARKER
#define SECONDARY_CURSOR_BACKGROUND ORANGE_BLAZE

// Warnings and Errors
#define WARNING ORANGE_GOLDEN
#define ERROR RED_FLAME
