#!/bin/sh

result=$(printf "%s\n%s" "$(cat "$1")" "fterm kak $1	?" |
    grep -Ev "^#|^$" |
    shuf |
    bemenu -p "$(basename "$1")" -F "$(printf '\t')" -sl20 --auto-select |
    cut -f1)
[ -z "$result" ] && exit
sh -c "$result"
printf '%s' "$0" | grep -- "-lock$" && exec "$0" "$@"
