#!/bin/sh

dir=$(mktemp -d)

mkfifo "$dir/stdin" "$dir/stdout" "$dir/stderr"

footclient -a floatpipe \
    background ' set_theme' '' \
    redirfd -r 0 "$dir/stdin" redirfd -w 1 "$dir/stdout" redirfd -w 2 "$dir/stderr" \
    "$@" &

cat "$dir/stdout" </dev/null &
cat "$dir/stderr" 1>&2 </dev/null &
cat >"$dir/stdin"
wait
rm -rf "$dir"
