#!/bin/sh
name="$1"
setval="$2"
relative="$3"

set -eu

harp_global() {
    path="$HOME/.local/share/harp/$name"
    mkdir -p "$path"
    printf %s "$path"
}

harp_local() {
    path="$HOME/.local/share/harp/$name"
    rel=$(printf %s "$relative" | sed 's/_/__/g;s@/@_@g')
    mkdir -p "$path$rel"
    printf %s "$path$rel"
}

relativity=local
[ -z "$relative" ] && relativity=global

while true; do
    sel=$(BQN -o '¯1↓∾∾⟜(@+10)¨∾⟨".,",⥊"aA"+⌜↕26⟩' | bemenu --auto-select -p "$1($relativity)")
    case "$sel" in
    .)
        sel=$(BQN -o '¯1↓∾∾⟜(@+10)¨⥊"aA"+⌜↕26' | bemenu --auto-select -p "$1(set$relativity)")
        if [ "$relativity" = global ]; then
            target="$(harp_global)/$sel"
        elif [ "$relativity" = local ]; then
            target="$(harp_local)/$sel"
        fi
        [ -z "$setval" ] && rm "$target" || printf %s "$setval">"$target"
        exit 2
        ;;
    ,)
        [ "$relativity" = global ] && relativity=local || relativity=global
        ;;
    *)
        if [ "$relativity" = global ]; then
            cat "$(harp_global)/$sel" 2>/dev/null
        elif [ "$relativity" = local ]; then
            cat "$(harp_local)/$sel" 2>/dev/null || cat "$(harp_global)/$sel" 2>/dev/null
        fi
        exit
        ;;
    esac
done
