#!/bin/sh
ln -sf "$1" ~/.config/themes/current-theme.h
cd ~/dotfiles
echo ':: Rebuilding dotfiles'
redo

echo ':: Updating wallpaper'
ln -sf "$(fd -e png . ~/Pictures/wallpapers/"$(basename -s .h "$1")" | shuf -n 1)" \
    ~/Pictures/wallpapers/wallpaper.png
killall wbg

echo ':: Reloading Kakoune'
kak -clear
for i in $(kak -l); do
    printf 'source %s' ~/.config/kak/autoload/colorscheme.kak | kak -p "$i"
done

clear
