#!/bin/sh
# Daemon to generate my wallpaper based on todo.txt

while true
do
    magick ~/Pictures/wallpaper_source.jpg \
           \( -pointsize 20 -font Iosevka -background none -gravity northwest -page 1000x1500 "text:$HOME/Documents/notes/todo.txt" -gravity northwest -geometry +100-10 \) \
           -composite ~/Pictures/wallpaper.png
    swww img -t none ~/Pictures/wallpaper.png
    entr -zp ~/Documents/notes/todo.txt
done
