#!/bin/sh
# Daemon to generate my wallpaper based on todo.txt

while true
do
    magick ~/Pictures/wallpaper_source.jpg \
           \( -fill "#d5c4a1" -pointsize 14 -font Iosevka -background none -gravity northwest -page 1000x1500 "text:$BRAIN_DIR/notes/todo.txt" -gravity northwest -geometry +100-10 \) \
           -composite ~/Pictures/wallpaper.png
    swww img -t none ~/Pictures/wallpaper.png
    echo "$BRAIN_DIR/notes/todo.txt" | entr -zp true
done
