#!/bin/sh

export XDG_CURRENT_DESKTOP=river

# Set the keyboard layout
# shellcheck disable=SC2046
change-keyboard $(head -n1 ~/.config/keyboards)
# In case stuff breaks
riverctl map normal Super Delete keyboard-layout us

pgrep -u "$USER" -x s6-svscan || s6-svscan ~/.local/service &

# Window Management
riverctl map normal Super+Shift Return spawn 'spawn foot'
riverctl map normal Super W close

riverctl map normal Super L focus-view next
riverctl map normal Super H focus-view previous

riverctl map normal Super+Shift L swap next
riverctl map normal Super+Shift H swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Hyphen focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Hyphen send-to-output previous

riverctl map normal Super Return zoom

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# 31 Tags
IFS="
"
for i in $(BQN -o '∾(•Fmt¨∘↕∘≠∾¨(@+9)∾¨⊢∾¨(@+10)˙) ¬∘∊⟜"HDWL"⊸/ ∾"1A"+↕¨9‿26'); do
    IFS="	"
    #shellcheck disable=SC2086
    set -- $i
    tags=$((1 << $1))
    riverctl map normal Super "$2" set-focused-tags "$tags"
    riverctl map normal Super+Shift "$2" set-view-tags "$tags"
    riverctl map normal Super+Control "$2" toggle-focused-tags "$tags"
    riverctl map normal Super+Shift+Control "$2" toggle-view-tags "$tags"
    IFS="
    "
done

riverctl map normal Super Comma focus-previous-tags

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags "$all_tags"
riverctl map normal Super+Shift 0 set-view-tags "$all_tags"

riverctl map normal Super Space spawn 'spawn normal-mode'
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
# Misc Config
riverctl set-repeat 50 300
riverctl focus-follows-cursor always
riverctl rule-add -app-id 'float*' float
riverctl rule-add -app-id FLTK float
riverctl rule-add -app-id "bar" csd
riverctl default-layout rivertile
